#!/usr/bin/env bash
set -Eeuo pipefail


if [ "${BASHLIB_PATH:-}" == "" ]; then
  SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")")" && pwd)"
  BASHLIB_PATH="$SCRIPT_DIR/../lib"
  if [ ! -d "$BASHLIB_PATH" ]; then
    echo "BASHLIB_PATH was not set and could not be found"
    exit 1
  fi
fi
export PATH="$BASHLIB_PATH:$PATH"
source bashlib-echo.sh

DOCKERFILE_PROJECT="Dockerfiles/$DOCK_X_NAME"

# Create the mount point to give it the right permissions
MOUNT_POINT="$PROJECT_ROOT/mount"
mkdir -p "$MOUNT_POINT"
chmod 0777 "$MOUNT_POINT"

# Cli
CLI_PATH="$DOCKERFILE_PROJECT/bin/$CLI_NAME"
if [[ ! -f "$CLI_PATH" ]]; then
  echo::err "CLI_NAME not found at $CLI_PATH"
  exit 1
fi
chmod +x "$CLI_PATH"

# Mount bashlib to edit the library
BASHLIB_PATH="$DOCKERFILE_PROJECT/bin/lib"
if [[ ! -d "$BASHLIB_PATH" ]]; then
  echo::err "BASHLIB_PATH ($BASHLIB_PATH) is not a directory"
  exit 1
fi

# Postgres CTL
POSTGRES_CTL="$PROJECT_ROOT/resources/postgres/postgres-ctl"
if [[ ! -f "$POSTGRES_CTL" ]]; then
  echo::err "POSTGRES_CTL ($POSTGRES_CTL) is not a file"
  exit 1
fi

# Mount profile.d to edit the bash script
PROFILE_D="$PROJECT_ROOT/resources/bash/profile/profile.d"
if [[ ! -d "$PROFILE_D" ]]; then
  echo::err "bash profile dir not found at $PROFILE_D"
  exit 1
fi

## Memory
# The default /dev/shm size for containers is 64MB. If the shared memory is exhausted you will encounter
# ERROR:  could not resize shared memory segment . . . : No space left on device.
# You will want to pass --shm-size=256MB

# Note: The entrypoint script is made so that any options passed to the docker command will be passed along to the postgres server daemon
# ie -c shared_buffers=256MB -c max_connections=200 are conf
# Ref: Database Conf at https://hub.docker.com/_/postgres/
# -d \
dock-x run \
  --mount type=bind,source="${CLI_PATH}",target=/usr/local/bin/"${CLI_NAME}" \
  -v "${MOUNT_POINT}":/var/lib/postgresql \
  -v "${PROFILE_D}":/etc/profile.d \
  -v "${BASHLIB_PATH}":/usr/local/lib/bash-lib \
  -v "$POSTGRES_CTL":/usr/local/bin/postgres-ctl \
  postgres \
  -c shared_buffers=256MB \
  -c max_connections=200
