#!/bin/bash

# What are the -c flags passed to supervisor-ctl
# The supervisor-ctl script is made so that any arguments will be passed along to the postgres server daemon
# If you pass for instance `-c` flags, you will change the postgres configuration
# -d \

## Scripts need to have execution
source bashlib-echo.sh

PROJECT_DIR=$(realpath "$(dirname "$0")/../")

# Create the mount point to give it the right permissions
MOUNT_POINT="$PROJECT_DIR/mount"
mkdir -p "$MOUNT_POINT"
chmod 0777 "$MOUNT_POINT"

# Mount dbctl to edit it
PX_X_PATH="$PROJECT_DIR/bin/pg-x"
if [[ ! -f "$PX_X_PATH" ]]; then
  echo::err "pg-x not found at $PX_X_PATH"
  exit 1
fi
chmod +x "$PX_X_PATH"

# Mount bashlib to edit the library
BASHLIB_PATH="$PROJECT_DIR/vendors/bash-lib/lib"
if [[ ! -d "$BASHLIB_PATH" ]]; then
  echo::err "BASHLIB_PATH ($BASHLIB_PATH) is not a directory"
  exit 1
fi

# Postgres CTL
POSTGRES_CTL="$PROJECT_DIR/resources/postgres/postgres-ctl"
if [[ ! -f "$POSTGRES_CTL" ]]; then
  echo::err "POSTGRES_CTL ($POSTGRES_CTL) is not a file"
  exit 1
fi

# Mount profile.d to edit the bash script
PROFILE_D="$PROJECT_DIR/resources/bash/profile/profile.d"
if [[ ! -d "$PROFILE_D" ]]; then
  echo::err "bash profile dir not found at $PROFILE_D"
  exit 1
fi

## Memory
# The default /dev/shm size for containers is 64MB. If the shared memory is exhausted you will encounter
# ERROR:  could not resize shared memory segment . . . : No space left on device.
# You will want to pass --shm-size=256MB

# Note: The entrypoint script is made so that any options passed to the docker command will be passed along to the postgres server daemon
# ie -c shared_buffers=256MB -c max_connections=200 are conf
# Ref: Database Conf at https://hub.docker.com/_/postgres/
dock-x run \
  --mount type=bind,source="${PX_X_PATH}",target=/usr/local/bin/pg-x \
  -v "${MOUNT_POINT}":/data \
  -v "${PROFILE_D}":/etc/profile.d \
  -v "${BASHLIB_PATH}":/usr/local/lib/bash-lib \
  -v "$POSTGRES_CTL":/usr/local/bin/postgres-ctl \
  postgres \
  -c shared_buffers=256MB \
  -c max_connections=200
