# https://fly.io/docs/reference/configuration/#auto-extend-volume-size-configuration
[[mounts]]
source = "data"
destination = "/data"
initial_size = "1gb"
snapshot_retention = 5
auto_extend_size_threshold = 80
auto_extend_size_increment = "1GB"
auto_extend_size_limit = "5GB"

# https://fly.io/docs/reference/configuration/#the-vm-section
[[vm]]
size = "shared-cpu-1x"
memory = "256mb"

[[mounts]]
destination = "/data"
source = "pg_data"

[metrics]
path = "/metrics"
port = 9187


