#!/usr/bin/env bash
# A exec to run bash and other command

set -euo pipefail


# The supervisor-ctl script is made so that any arguments will be passed along to the postgres server daemon
# If you pass for instance `-c` flags, you will change the postgres configuration
# -d \
docker run \
  --name postgres-exec \
  --rm \
  -ti \
  --env-file secret.env \
  --user 1000:1000 \
  --group-add postgres \
  "${DOCKER_REGISTRY:-docker.io}"/"${DOCKER_USER}"/"${DOCKER_REPO}":"$DOCKER_TAG" \
  "$@"

