#!/bin/bash

# Setting strictly bash
set -Eeuo pipefail

SUPERVISOR_CONF_PATH=${SUPERVISOR_CONF_PATH:-/supervisord.conf}

LOG_HOME=${LOG_HOME:-/var/log}

# Get the bash environments
for file in /etc/profile.d/*.sh; do
    # shellcheck disable=SC1090
    [ -r "$file" ] && source "$file"
done
unset file


# Create log dirs
# The log directory are not created and just stop supervisor
# https://github.com/Supervisor/supervisor/issues/120#issuecomment-209292870
export SQL_EXPORTER_LOG=${LOG_HOME}/sql-exporter/sql-exporter.log
export POSTGRES_EXPORTER_LOG=${LOG_HOME}/postgres-exporter/postgres-exporter.log
export POSTGRES_LOG=${LOG_HOME}/postgres/postgres.log
LOGS=(
    "$SQL_EXPORTER_LOG"
    "$POSTGRES_EXPORTER_LOG"
    "$POSTGRES_LOG"
)
for LOG in "${LOGS[@]}"; do
    LOG_PARENT=$(dirname "$LOG")
    mkdir -p "$LOG_PARENT"
    touch "$LOG"
done

export POSTGRES_ARGS="${*}"
echo_info "postgres args: ${POSTGRES_ARGS}"

# we set the `c` to avoid the below warning:
# UserWarning: Supervisord is running as root and it is searching
# for its configuration file in default locations (including its current working directory);
# you probably want to specify a "-c" argument specifying
# an absolute path to a configuration file for improved security.
#
# We run it with `exec` so that it respond to Ctrl+z (SIGINT)
#
exec supervisord -c "$SUPERVISOR_CONF_PATH"
